const products = [
  {
    id: 1,
    name: "Handmade Ceramic Mug",
    description: "Beautiful handcrafted ceramic mug with unique glaze patterns",
    category: "Home & Living",
    price: 24.99,
    stock: 15,
    rating: 4.5,
    reviews: 24,
    sales: 145,
    revenue: 3624,
    views: 892,
    conversion: 16.3,
    status: "Active",
    image: "🪔"
  },
  {
    id: 2,
    name: "Organic Cotton Tote Bag",
    description: "Eco-friendly tote bag made from 100% organic cotton",
    category: "Fashion",
    price: 18.5,
    stock: 32,
    rating: 4.8,
    reviews: 42,
    sales: 132,
    revenue: 2442,
    views: 756,
    conversion: 17.5,
    status: "Active",
    image: "👜"
  },
  {
    id: 3,
    name: "Artisan Candle Collection",
    description: "Hand-poured soy candles with natural essential oils",
    category: "Home & Living",
    price: 45.99,
    stock: 24,
    rating: 4.7,
    reviews: 56,
    sales: 124,
    revenue: 5703,
    views: 1204,
    conversion: 10.3,
    status: "Active",
    image: "🕯️"
  },
  {
    id: 4,
    name: "Vintage Notebook Set",
    description: "Set of 3 vintage-style notebooks with premium paper",
    category: "Stationery",
    price: 32,
    stock: 8,
    rating: 4.2,
    reviews: 18,
    sales: 98,
    revenue: 3136,
    views: 542,
    conversion: 18.1,
    status: "Low Stock",
    image: "📓"
  },
  {
    id: 5,
    name: "Hand-knit Scarf",
    description: "Cozy wool scarf handmade with premium yarn",
    category: "Fashion",
    price: 28,
    stock: 3,
    rating: 4.6,
    reviews: 31,
    sales: 76,
    revenue: 2128,
    views: 432,
    conversion: 17.6,
    status: "Low Stock",
    image: "🧣"
  }
];

export default products;